export enum ActionType {
  activeSlotClear = 'activeSlotClear',
  activeSlotUpdate = 'activeSlotUpdate',
  authStateChanged = 'authStateChanged',
  clearNavigation = 'clearNavigation',
  createTab = 'createTab',
  deleteCancel = 'deleteCancel',
  deleteConfirm = 'deleteConfirm',
  deletePrompt = 'deletePrompt',
  discardChangesCancel = 'discardChangesCancel',
  discardChangesConfirm = 'discardChangesConfirm',
  discardChangesPrompt = 'discardChangesPrompt',
  enterEditMode = 'enterEditMode',
  fetchTabsEnd = 'fetchTabsEnd',
  fetchTabsStart = 'fetchTabsStart',
  loaderDisplay = 'loaderDisplay',
  loaderHide = 'loaderHide',
  searchParamsReady = 'searchParamsReady',
  setStripeSubscription = 'setStripeSubscription',
  setTab = 'setTab',
  setTabListParams = 'setTabListParams',
  signInFinish = 'signInFinish',
  signInStart = 'signInStart',
  updateTab = 'updateTab',
}
