export enum ActionType {
  activeSlotClear = 'activeSlotClear',
  activeSlotUpdate = 'activeSlotUpdate',
  authStateChanged = 'authStateChanged',
  clearNavigation = 'clearNavigation',
  createTab = 'createTab',
  discardChangesCancel = 'discardChangesCancel',
  discardChangesConfirm = 'discardChangesConfirm',
  discardChangesPrompt = 'discardChangesPrompt',
  enterEditMode = 'enterEditMode',
  loaderDisplay = 'loaderDisplay',
  loaderHide = 'loaderHide',
  setTab = 'setTab',
  signInFinish = 'signInFinish',
  signInStart = 'signInStart',
  updateTab = 'updateTab',
}
